# for amd64/cpu
# see: https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-cpu

FROM amd64/python:3-bookworm
ARG BIN_VERSION=<unknown>

RUN apt-get -y update \
    && apt-get install --no-install-recommends -y \
        curl git zip libpython3-dev python3-opencv libgl1 libglib2.0-0 libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
COPY ./*.py ./requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
COPY ./enrichment-prompts /

WORKDIR /app
RUN curl -f -L -O https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt
ENV DM_DOCKER_ALSO_BIND="*:2856"
HEALTHCHECK CMD curl -s --max-time 2 --fail http://localhost:2856/health || exit 1
ENTRYPOINT ["python3", "main.py"]

LABEL license="GPL-3.0"
LABEL maintainer="Chris Dzombak <https://www.dzombak.com>"
LABEL org.opencontainers.image.authors="Chris Dzombak <https://www.dzombak.com>"
LABEL org.opencontainers.image.url="https://github.com/cdzombak/driveway-monitor"
LABEL org.opencontainers.image.documentation="https://github.com/cdzombak/driveway-monitor/blob/main/README.md"
LABEL org.opencontainers.image.source="https://github.com/cdzombak/driveway-monitor.git"
LABEL org.opencontainers.image.version="${BIN_VERSION}"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.title="driveway-monitor"
LABEL org.opencontainers.image.description="Receive customizable, AI-powered notifications when someone arrives in your driveway."
