# for amd64/cuda
# see: https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile

FROM amd64/python:3.11-bookworm
ARG BIN_VERSION=<unknown>

RUN apt-get -y update \
    && apt-get install --no-install-recommends -y \
        curl libgl1 libpython3-dev python3-opencv unzxip gcc g++ \
    && rm -rf /var/lib/apt/lists/*

# Avoid DDP error "MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library" https://github.com/pytorch/pytorch/issues/37377
# per https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile
ENV MKL_THREADING_LAYER=GNU

RUN mkdir /app
COPY ./*.py ./requirements.txt /app/
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1
RUN pip install nvidia-tensorrt
RUN pip install -r /app/requirements.txt
COPY ./enrichment-prompts /

WORKDIR /app
RUN curl -f -L -O https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt
ENV DM_DOCKER_ALSO_BIND="*:2856"
HEALTHCHECK CMD curl -s --max-time 2 --fail http://localhost:2856/health || exit 1
ENTRYPOINT ["python3", "main.py"]

LABEL license="GPL-3.0"
LABEL maintainer="Chris Dzombak <https://www.dzombak.com>"
LABEL org.opencontainers.image.authors="Chris Dzombak <https://www.dzombak.com>"
LABEL org.opencontainers.image.url="https://github.com/cdzombak/driveway-monitor"
LABEL org.opencontainers.image.documentation="https://github.com/cdzombak/driveway-monitor/blob/main/README.md"
LABEL org.opencontainers.image.source="https://github.com/cdzombak/driveway-monitor.git"
LABEL org.opencontainers.image.version="${BIN_VERSION}"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.title="driveway-monitor"
LABEL org.opencontainers.image.description="Receive customizable, AI-powered notifications when someone arrives in your driveway."
