---
version: "3"

tasks:
  fmt:
    cmds:
      - ruff format
      - prettier --write .
    desc: Format (Python, Prettier)
  lint:
    cmds:
      - ruff check
      - prettier --check .
      - actionlint .github/workflows/*.yml
    desc: Lint (Python, Prettier, GitHub Actions)
  test:
    cmds:
      - python -m unittest tests/*.py
    desc: Run tests
  build:
    deps: [build-amd64, build-arm64]
    desc: Build images for all supported platforms/architectures
  build-amd64:
    cmds:
      - docker build . -f Dockerfile-amd64
  build-arm64:
    cmds:
      - docker build . -f Dockerfile-arm64
